[build]
  command = "npm run build"
  publish = ".next/export"
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  # Отключён плагином через переменную среды
