[build]
  command = "npm run build"
  publish = ".next/export"
  environment = { 
    NETLIFY_NEXT_PLUGIN_SKIP = "true", 
    NODE_VERSION = "18.20.2"
  }

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
